# Generated by Django 4.2.13 on 2024-07-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "E_commerce_app",
            "0002_rename_status_order_complete_remove_order_address_and_more",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="E_commerce_app.category",
            ),
            preserve_default=False,
        )
    ]
